#!/bin/bash

echo 'This will overwrite configs and install/uninstall packages, continue? (Y/n)'
read -rp 'Answer: '  answer

if [[ ${answer:-Y} =~ ^[Yy]$ ]]; then
   sudo -v

   source ./installscript

   exec "$BASH"
fi


