#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo 'This will overwrite configs and install/uninstall packages, continue? (Y/n)'
read -rp 'Answer: '  answer

if [[ ${answer:-Y} =~ ^[Yy]$ ]]; then
   sudo -v

   source $SCRIPTPATH/installscript

   exec "$BASH"
fi


