#!/bin/bash

set -x
SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo '###########################################################################'
echo '# Install packages (apt)...'
sudo apt -y install \
  apt-transport-https \
  awscli \
  ca-certificates \
  curl \
  git \
  git-gui \
  gnome-tweak-tool \
  gnupg \
  htop \
  jq \
  libmysqlclient-dev \
  lsb-release \
  network-manager-openvpn \
  network-manager-openvpn-gnome \
  python3 \
  python3-pip \
  python3-venv \
  qbittorrent \
  terminator \
  vim

echo '###########################################################################'
echo '# Remove packages (apt)...'
sudo apt -y remove ibus

echo '###########################################################################'
echo '# Install packages (snap)...'
sudo snap install slack --classicg
sudo snap install --classic

echo '###########################################################################'
echo '# Install packages (npm)...'
npm install --global gsts

echo '###########################################################################'
echo '# Install albert...'
curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -
echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_21.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
sudo wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_21.04/Release.key -O "/etc/apt/trusted.gpg.d/home:manuelschneid3r.asc"
sudo apt -y update
sudo apt -y install albert

echo '###########################################################################'
echo '# Install PIPX (https://pypa.github.io/pipx/)...'
python3 -m pip install --user --upgrade pipx
python3 -m pipx ensurepath

echo '###########################################################################'
echo '# Install Docker...'
sudo apt -y remove docker docker-engine docker.io containerd runc
sudo apt -y update

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
  sudo gpg -y --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt -y update
sudo apt -y install docker-ce docker-ce-cli containerd.io

sudo groupadd docker
sudo usermod -aG docker $USER

echo '###########################################################################'
echo '# Install Mysql-Workbench...'
workbench="mysql-apt-config_0.8.19-1_all.deb"
sudo wget https://dev.mysql.com/get/$workbench
sudo apt -y install ./$workbench
rm -rf ./$workbench
sudo apt -y update
sudo apt -y install mysql-workbench-community

echo '###########################################################################'
echo '# Install Docker-compose...'
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

echo '###########################################################################'
echo '# Install XSV...'
sudo curl -L "https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz" | sudo tar xvz -C /usr/local/bin
sudo chmod +x /usr/local/bin/xsv

echo '###########################################################################'
echo '# Install PINTA...'
sudo add-apt-repository -y ppa:pinta-maintainers/pinta-stable
sudo apt -y update
sudo apt -y install pinta

echo '###########################################################################'
echo '# Install VLC...'
sudo apt -y install vlc

echo '###########################################################################'
echo '# Install chrome...'
sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt -y update
sudo apt -y install google-chrome-stable

echo '###########################################################################'
echo '# Install VeraCrypt...'
veracrypt="veracrypt-1.24-Update7-Ubuntu-21.04-amd64.deb"
sudo wget https://launchpad.net/veracrypt/trunk/1.24-update7/+download/$veracrypt
sudo apt -y install ./$veracrypt
rm -rf ./veracrypt*

echo '###########################################################################'
echo '# Install Terraform...'
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository -y "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt -y update
sudo apt -y install terraform
terraform -install-autocomplete

echo '###########################################################################'
echo '# Install Kubernetes...'
kubLastVersion=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
curl -LO https://storage.googleapis.com/kubernetes-release/release/$kubLastVersion/bin/linux/amd64/kubectl
chmod +x ./kubectl
sudo mv ./kubectl /usr/local/bin/kubectl

echo '###########################################################################'
echo '# Install Helm...'
curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

echo '###########################################################################'
echo '# Setup git...'
git config --global user.name vdauchy
git config --global push.default current
git config --global core.editor vim

echo '###########################################################################'
echo '# Setup bashrc...'
grep -qxF '. ~/.bash_customs' ~/.bashrc || echo '. ~/.bash_customs' >> ~/.bashrc

echo '###########################################################################'
echo '# Extends bashrc...'
cp -f $SCRIPTPATH/shell/.bash_customs ~/.bash_customs
cp -f $SCRIPTPATH/shell/.bash_aliases ~/.bash_aliases
cp -n $SCRIPTPATH/shell/.github ~/.github
cp -n $SCRIPTPATH/shell/.blackfire ~/.blackfire

echo '###########################################################################'
echo '# Setups Configs...'

mkdir -p ~/.config/terminator
cp -f $SCRIPTPATH/profile/.config/terminator/config ~/.config/terminator/config

mkdir -p ~/.config/vlc
cp -f $SCRIPTPATH/profile/.config/vlc/vlcrc ~/.config/vlc/vlcrc

echo '###########################################################################'
echo '# Upgrade...'
sudo apt -y upgrade

echo '###########################################################################'
echo '# Cleanup...'
sudo apt -y autoremove