#!/bin/bash

echo '# Install packages...'
sudo apt install \
  jq \
  git \
  git-gui \
  htop \
  terminator \
  vim

echo '# Install phpstorm...'
sudo snap install phpstorm --classic

echo '# Install chrome...'
sudo sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update
sudo apt-get install google-chrome-stable

echo '# Setup git...'
git config --global user.name vdauchy
git config --global push.default current
git config --global core.editor vim

echo '# Setup bashrc...'
grep -qxF '. ~/.bash_customs' ~/.bashrc || echo '. ~/.bash_customs' >> ~/.bashrc

echo '# Extends bashrc...'
cp -f ./shell/.bash_customs ~/.bash_customs
cp -f ./shell/.bash_aliases ~/.bash_aliases

echo '# Setups Configs...'
mkdir -p ~/.config/terminator
cp -f ./.config/terminator/config ~/.config/terminator/config

echo '# Cleanup...'
sudo apt autoremove -y